#Name: api-api
#Host: 0.0.0.0
#Port: 8888

APP_ENV: dev

APP_SYSTEM:
  PORT: 3000
  IPV4:
    A: 192
    B: 168
    C: 0
    D: 22

Mysql:
  dns: root:DHHdfghdfg@578571.@tcp(124.220.164.90:3306)/qqchat?charset=utf8mb4&parseTime=True&loc=Local
  LOG_DIR: logs/sql                  #mysql 日志目录

Logger: # 日志
  LOG_DIR: logs/service

Jwt:
  key: "RQmFvMjFPHZ8hnNz8bNuGU_kmGTQugQLrFHhx6zoYcA="
  expiresIn: 86400             # 秒

Redis:
  Addr: "8.134.181.156:8379"                                #Redis服务器地址6379
  Password: "dfgopwertgkwpeirgmwp4tFLDKMVaserogi2jkwp4t9gkwefgotqp3r49ifjqp3eifm13plarfmpqef293485erlfdmawdwergi2j3rpfiqmef1"    #认证密码（若无则留空）
  DB: 3                                                 #数据库索引（0-15）
  PoolSize: 50                                          #最大连接数
  MaxIdleConns: 8                                       #最大空闲连接数
  MinIdleConns: 2                                      #最小空闲连接数
  DialTimeout: 5                                       #连接超时时间   秒